---
apiVersion: v1
kind: Service
metadata:
  name: nginx-servic
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      # nodeSelector:
      #   kubernetes.io/hostname: worker1
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80