---
# tasks file for config-docker
  - name: Copier daemon.json
    ansible.builtin.template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
  
  - name: Relancer Service Docker
    ansible.builtin.service:
      name: docker
      state: restarted