---
# tasks file for roles/kubernetes-node
  - name: Display default IPv4 address of mgr1
    debug:
      msg: "Host IP address: {{ hostvars['mgr1']['ansible_default_ipv4']['address'] }}"

  - name: TCP port 6443 on master is reachable from worker
    wait_for: "host={{ hostvars['mgr1']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

  - name: join cluster
    shell: "{{ hostvars['mgr1'].join_command }} >> node_joined.log"
    args:
      chdir: /home/ubuntu
      creates: node_joined.log