apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-volume
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi