apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registre-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 10Gi