apiVersion: v1
kind: PersistentVolume
metadata:
  name: registre-volume
  labels:
    type: local
  namespace: app-m2ssi
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/registre"