---
# tasks file for roles/registry
  - name: debug
    debug:
      var: ansible_default_ipv4.address

  - name: Copier daemon.json
    ansible.builtin.template:
      src: daemon.json.j2
      dest: /etc/docker/daemon.json
  
  - name: Relancer Service Docker
    ansible.builtin.service:
      name: docker
      state: reloaded
  
  - name: Deploiement d'un registre docker
    community.docker.docker_container:
      name: registry
      image: registry:2
      state: started
      recreate: false
      restart: false
      detach: true
      restart_policy: "always"
      ports:
        - "5000:5000"
  
  - name: Install du module kubernetes.core.k8s
    pip:
      name: kubernetes
  
  # commande:kubectl create secret docker-registry reg-secret \
  # --docker-server=localhost:5000 \
  # --docker-username=VOTRE_UTILISATEUR \
  # --docker-password=VOTRE_MOT_DE_PASSE \
  # --docker-email=VOTRE_EMAIL
  # ou
  # commande:kubectl create secret docker-registry docker-hub-sec --docker-username=VOTRE_UTILISATEUR --docker-password=VOTRE_MOT_DE_PASSE
  - name: creation d'un secret kubernetes
    kubernetes.core.k8s:
      state: present
      definition: 
        apiVersion: v1
        kind: Secret
        # type: Opaque       
        metadata:
          name: "docker-hub-sec"
          namespace: "default"
        # type: kubernetes.io/dockerconfigjson
        data:
          password: password
          username: test
          #config_data.json: "lookup('pipe', 'echo -n {\"auths\":{\"localhost:5000\":{\"test\":\"' + VOTRE_UTILISATEUR + '\",\"test\":\"' + VOTRE_MOT_DE_PASSE + '\",\"email\":\"' + VOTRE_EMAIL + '\"}}}') | b64encode }}"
#https://stackoverflow.com/questions/59203583/how-can-i-create-a-kubernetes-secret-with-ansible
...
# commandes a faire après:
# docker pull nginx
# docker tag nginx 10.164.246.248:5000/nginx
# docker push 10.164.246.248:5000/nginx
# apt install nano
# nano testpod.yml

# fonctionne
# apiVersion: v1
# kind: Pod
# metadata:
#   namespace: default
#   name: test
#   labels:
#     app: mon-app
# spec:
#   containers:
#   - name: mon-conteneur
#     image: 10.164.246.248:5000/nginx
#   imagePullSecrets:
#   - name: docker-hub-sec

# fonctionne aussi:
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mon-deploiement
#   namespace: default
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: mon-app
#   template:
#     metadata:
#       labels:
#         app: mon-app
#     spec:
#       containers:
#       - name: mon-conteneur
#         image: 10.164.246.248:5000/nginx
#       imagePullSecrets:
#       - name: docker-hub-sec

# pour afficher infos : kubectl describe pods -n default
# erreur : https://stackoverflow.com/questions/59844553/kubernetes-failed-to-pull-image-server-gave-http-response-to-https-client
# kubectl apply -f testpod.yaml
# pour afficher les pods ainsi que leur node:
# kubectl get pods -o wide
# pour supprimer les pods:
# kubectl delete pods --all
