---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # Base64 encoded password
  MYSQL_DATABASE: cHJvamV0X20yc3Np  # Base64 encoded database name
  MYSQL_USER: YWRtaW4=  # Base64 encoded username
  MYSQL_PASSWORD: b0ptaWpsRzVEZEJJWThRdHFMVjRPUjI0TllycnVJbVBzSA==
  # oJmijlG5DdBIY8QtqLV4OR24NYrruImPsH en base64