---
- name: Create Projet infrastructure LXD containers
  hosts: localhost
  tasks:
    # - name: Delete bridge networks
    #   command: brctl delbr "{{ item }}"
    #   become: true
    #   with_items:
    #     - br01
    #     - br02
    # - name: Create bridge networks
    #   command: brctl addbr "{{ item }}"
    #   become: true
    #   with_items:
    #     - br01
    #     - br02
    # - name: ip link set dev br01 up
    #   command: ip link set dev "{{ item }}" up
    #   become: true
    #   with_items:
    #     - br01
    #     - br02

    # - name: lxc profile copy default k8s
    #   community.general.lxd_profile_copy:
    #     name: k8s
    #     copy_from: default
    #     state: present

    - name: Create all LXD virtual machines 
      community.general.lxd_container:
        name: "{{ item }}"
        ignore_volatile_options: true
        state: started
        type: virtual-machine
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/focal/amd64
        profiles: ["k8s"]
        # wait_for_ipv4_addresses: true
      with_items: "{{ groups['all'] }}"

- name: Docker/Kubernetes roles
  hosts: k8s
  connection: lxd
  roles:
    - docker
    - kubernetes

- name: Kubernetes master roles
  hosts: mgr
  connection: lxd
  roles:
    - kubernetes-master

- name: Kubernetes worker roles
  hosts: worker
  connection: lxd
  roles:
    - kubernetes-node

- name: Add nodes to Kubernetes cluster
  hosts: mgr
  connection: lxd
  tasks:
    - name: Add nodes to Kubernetes cluster
      shell: kubectl label node "{{ item }}" node-role.kubernetes.io/worker=worker
      with_items: "{{ groups['worker'] }}"

- name: Deploy Jenkins
  hosts: jenkins
  connection: lxd
  become: true
  roles:
    - jenkins

- name: Registry roles
  hosts: registry
  connection: lxd
  become: true
  roles:
    - registry