---
- name: Create Projet infrastructure LXD containers
  hosts: localhost
  tasks:
    # - name: Delete bridge networks
    #   command: brctl delbr "{{ item }}"
    #   become: true
    #   with_items:
    #     - br01
    #     - br02
    # - name: Create bridge networks
    #   command: brctl addbr "{{ item }}"
    #   become: true
    #   with_items:
    #     - br01
    #     - br02
    # - name: ip link set dev br01 up
    #   command: ip link set dev "{{ item }}" up
    #   become: true
    #   with_items:
    #     - br01
    #     - br02

    # - name: lxc profile copy default k8s
    #   community.general.lxd_profile_copy:
    #     name: k8s
    #     copy_from: default
    #     state: present

    - name: Create all LXD containers 
      community.general.lxd_container:
        name: "{{ item }}"
        ignore_volatile_options: true
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: simplestreams
          alias: ubuntu/focal/amd64
        profiles: ["k8s"]
        # wait_for_ipv4_addresses: true
      with_items: "{{ groups['lxd_containers'] }}"

- name: Docker/Kubernetes roles
  hosts: lxd_containers
  connection: lxd
  roles:
    - docker
    - kubernetes

- name: Kubernetes master roles
  hosts: mgr
  connection: lxd
  roles:
    - kubernetes-master

- name: Kubernetes worker roles
  hosts: worker
  connection: lxd
  roles:
    - kubernetes-node