---
- name: Suppresion cluster
  hosts: localhost
  tasks:
    - name: Destroy a container
      community.general.lxd_container:
        name: '{{ item }}'
        state: absent
        type: virtual-machine
      with_items: "{{ groups['all'] }}"
#https://www.youtube.com/watch?v=xYk6qCyXOY4
...