---
- name: Kubernetes master roles
  hosts: mgr
  connection: lxd
  roles:
    - kubernetes-master

# - name: Deploy Jenkins
#   hosts: jenkins
#   connection: lxd
#   become: true
#   roles:
#     - jenkins
#     - docker