---
# tasks file for roles/jenkins
  - name: Install packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - fontconfig
        - openjdk-17-jre
  - name: Add Jenkins key
    shell: wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
  
  - name: Add Jenkins repository
    shell: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  
  - name: Install Jenkins
    apt:
      name: jenkins
      state: present